### ISSUE TITLE
Enable missing strings to be translated

### ISSUE THREAD

**Issue by ovari** [tchx84/Flatseal#148]
Please enable the following strings to be translated:
* Share
* Socket
* Device
* Allow
* Filesystem
* Persistent
* Environment
* System Bus
* Session Bus

They are headings as shown in the image below
![kép](https://user-images.githubusercontent.com/17465872/94990076-ad097200-05bc-11eb-9df8-8ecfeb5a6b2b.png)

Thank you

**Comment by ovari** [comment]
@tchx84 please advise if we need to do anything else. Thank you

**Comment by tchx84** [comment]
Hey @ovari , the reason I leave these untranslated is because they match the `flatpak-override` options. Their goal is to make it easier to map `flatpak-overrides` options with Flatseal groups.

Since `flatpak-override` options are not translated, e.g it's always `--allo=blah`, I kept these untranslated.
