### ISSUE TITLE
Add XDG directories toggleable as options

### ISSUE THREAD

**Issue by TheEvilSkeleton** [tchx84/Flatseal#165]
Not everybody understands `xdg-documents`, `xdg-videos`, etc. because they don't know what XDG is. I'd advise to add toggles enable `xdg-desktop`, `xdg-pictures`, `xdg-videos`, `xdg-documents`, `xdg-downloads` and `xdg-music` directories to make it a bit more user friendly.

**Comment by tchx84** [comment]
Not a bad idea, but I think the permissions UI is already too cluttered, and we need to balance these things.

Note that the users don't _need_ to know that `xdg-downloads` exists, as they can simply type `~/Downloads` (or whatever the directory is called according to their locale). If they see `xdg-download`, because an app is including it by default, flatseal currently displays  a tooltip with a brief explanation.

**Comment by tchx84** [comment]
If you can think of some other approach to improve the usability of this, feel free to re-open / update this or create a new issue.
