### ISSUE TITLE
Application list hidden when current app has larger title

### ISSUE THREAD

**Issue by razzeee** [tchx84/Flatseal#273]
Not 100% sure it's the cause, but all my apps look like this in this size:

![image](https://user-images.githubusercontent.com/5943908/115921581-fb5c6080-a47b-11eb-9743-557c680098a6.png)

Just google music will collapse the side panel when it's opened 
![image](https://user-images.githubusercontent.com/5943908/115921666-15963e80-a47c-11eb-856a-592e82f659c3.png)

This feels kinda inconsistent and is probably not wanted?

**Comment by tchx84** [comment]
Hello again :laughing: ,

This is actually the expected behavior and, even though its weird, is the compromise needed for Flatseal to adapt to mobile screens.

Technically speaking. The long title is literally expanding the permissions section, so the UI will collapse the applications list to make sure that the application window can still fit on the screen. The size-negotiation logic in GTK3 is _quite_ different from, let's say, the web, so there are all sorts of "borderline" behaviors like this when trying to make adaptive UIs. You just happen to have sized the window in one of those sweat spots of "borderlinerness".

For the moment I have spent enough time on "not fixing" this, so I will close this issue, but please feel free to re-open it if it's something you would be interested in tinkering with.
