### ISSUE TITLE
Sort apps by name, not app ID

### ISSUE THREAD

**Issue by wjt** [tchx84/Flatseal#296]
Currently, Flatseal appears to sort apps by their app ID. For example, TuxGuitar (`ar.com.tuxguitar.TuxGuitar`) sorts before Arduino IDE (`cc.arduino.arduinoide`), even though T is much further through the alphabet than A.

I think it would be preferable to sort apps by their name, rather than Flatpak app ID. The reversed-DNS name is an implementation detail. As well as making it easier to skim-read the list, sorting by name would be consistent with Settings → Applications and the list of apps displayed in Parental Controls. Here is a side-by-side comparison of Settings and Flatseal.

![Capture d’écran de 2021-05-18 14-28-03](https://user-images.githubusercontent.com/86760/118660426-19e91980-b7e6-11eb-88cb-9a233a06caf9.png)

**Comment by wjt** [comment]
Though I accept that it does have the nice behaviour that all the Endless apps, and all the Sugar apps, and all the first-party GNOME apps, get grouped together.

**Comment by tchx84** [comment]
> Though I accept that it does have the nice behaviour that all the Endless apps, and all the Sugar apps, and all the first-party GNOME apps, get grouped together.

yes, that's exactly why I went for appid, but is not like I made an UX evaluation either...

**Comment by Doomsdayrs** [comment]
How about having an option? Surely swapping between two different sorts is not too hard

**Comment by ssokolow** [comment]
This is currently the number-one most frustrating thing about using Flatseal, because I just *don't* think to use search/filter as my primary navigation mode, so I wind up having to scan through the entire list every time I use it.

Humans don't think in reverse DNS naming. It is not intuitive at all, and it prevents the kind of "human binary search" you'd use in something like a print dictionary, phone book, or other sorted reference book.

Imagine how painful it'd be if you sorted a phone book by the phone numbers because they used to represent a hierarchical narrowing of geographical regions. 

To explain that reference to anyone who never thought about anything finer-grained than the area code, here's how a North American phone number like +1-416-123-4567 was designed:

* +1 (Country code... though technically +1 is all of North America)
* 416 (Area code. Originally the city of Toronto in Ontario, Canada, before they outgrew having just one)
*  123 (Local exchange. Before automated exchanges, a local phone number would be something like JONES-4567 and the operator would call up an operator at the JONES exchange and ask them to patch through to the numbered liine before unplugging the caller from their headset and plugging them into the now connected line. Long-distance, [assuming it was possible](https://www.youtube.com/watch?v=SS5X5BkIKpM), would be something like "Operator, get me Chicago, MARKS-9090.")
* 4567 (Phone number within the local exchange)

**Comment by tchx84** [comment]
let's see how this goes...
