### ISSUE TITLE
write settings to ~/.var/app/[AppName] instead of ~/.local/share/flatpak

### ISSUE THREAD

**Issue by amerkheir** [tchx84/Flatseal#463]
you write the settings in file: ~/.local/share/flatpak/overrides/[AppName];
instead think of writing the settings in file: ~/.var/app/[AppName]/overrides (for instance), the important is to be inside ~/.var/app/[AppName].

**Comment by rusty-snake** [comment]
1. They are written to `${XDG_DATA_DIR}/flatpak/overrides` because  this is the place where flatpak reads them. The only thing that flatseal could do are symlinks. You would need to open an feature request at flatpak. But don't do so, see 2.
2. **`~/.var/app/<app-id>` is writable by the application.** Storing the sandbox configuration there would make the sandbox broken by design.

**Comment by amerkheir** [comment]
Thanks a lot
But could it be written to some where inside ~/.var (~/.var/flatpak/overrides for example).
Thanks a lot
Have a nice day
________________________________

**Comment by rusty-snake** [comment]
Yes, the following works:
```bash
mv ~/.local/share/flatpak/overrides ~/.var/app/com.github.tchx84.Flatseal/overrides
ln -s ~/.var/app/com.github.tchx84.Flatseal/overrides ~/.local/share/flatpak/overrides
```

**Comment by amerkheir** [comment]
Thanks a lot
Have a nice day
________________________________

**Comment by tchx84** [comment]
thanks @rusty-snake for clarifying :)
