### ISSUE TITLE
Flatseal shows no applications

### ISSUE THREAD

**Issue by AirisLuna** [tchx84/Flatseal#502]
Basically the same thing as: https://github.com/tchx84/Flatseal/issues/455

In my case I moved flatpak installation to  /home/flatpak after installing at / , and I think this might have messed up something. I tried everything from the previous thread except the recompiling as I'm not good enough to understand what that does, or how to do it.

![Screenshot_20221226_062054](https://user-images.githubusercontent.com/13425006/209543424-366fa057-38b5-4abc-88aa-910385fe33f1.png)

And here is my Flatseal screen

**Comment by rusty-snake** [comment]
What does `flatpak info -M com.github.tchx84.Flatseal` show?

Basicly this is what happens if you revoke `org.freedesktop.impl.portal.PermissionStore=talk`.

Try to `flatpak override --user --reset com.github.tchx84.Flatseal`.

@tchx84 this is a bug, right? Because flatseal should still be able to query all installed flatpaks and change `xdg-data/flatpak/overrides/com.example.App`. So users can undo this w/o using the commandline.

Funny removing `org.freedesktop.impl.portal.PermissionStore` also toggles filesystem permissions. Likely relates to #449 and `!host:reset` in `globals`. Need to investigate.

**Comment by tchx84** [comment]
Hi @AirisLuna , when you say `I moved flatpak installation`, what **exactly** do you mean? How did you move it?

**Comment by ACR-Jeff** [comment]
I have the exact same issue, I have installed flatpak to an "Applications" folder in my Home directory, Per these instructions on Flatpak https://docs.flatpak.org/en/latest/tips-and-tricks.html#adding-a-custom-installation

**Comment by ACR-Jeff** [comment]
Fixed it by following the steps in the Documentation "Use custom FLATPAK_USER_DIR" Change the path's to your Flatpak installation path, paste it into terminal and execute, Then run Flatseal, Worked great, https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#use-custom-flatpak_user_dir

**Comment by tchx84** [comment]
@ACR-Jeff excellent, thanks for letting us know.

**Comment by tfardet** [comment]
@tchx84 would you consider adding a message if no apps are found, with a link to the documentation?
E.g. "No apps found, are you using a custom directory for your flatpaks? If so, see our documentation : https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#use-custom-flatpak_user_dir"
