### ISSUE TITLE
[feature request] Setting environment variables

### ISSUE THREAD

**Issue by ghost** [tchx84/Flatseal#51]
Thanks for developing this great app!

Would you consider adding the ability for setting and viewing custom environment variables, as one would do with `flatpak override --env=VARIABLE=value name.of.app`?

Maybe the widgets used for setting custom folder access are suitable for this too.

**Comment by tchx84** [comment]
ill explore it, thanks.

**Comment by tchx84** [comment]
I explored this, and l need more time to think how to do this without making the code too obscure (the current approach is just too much of a hack). But I will.

**Comment by stobbsm** [comment]
This is a feature I would really like. I'll look at your code and help if I can, but I'm not a JS dev, so it may take some time to learn.

**Comment by tchx84** [comment]
> This is a feature I would really like. I'll look at your code and help if I can, but I'm not a JS dev, so it may take some time to learn.

Hey Matthew, 

Thanks.

One piece of advice though. What I learnt from that experiment branch (mentioned in this issue) is that Flatseal needs a big refactor of the permissions model. I already did the first steps, but there is still more to be done to handle different kind of permissions without ending up with too much spaghetti code.

What I have in mind, so far, is to handle different sections of the overrides file in different sub-modules, so each sub-module can handle specific logic for how those sections behaves (instead of having a one big model, like it does now, with a lot of edge cases).
