### ISSUE TITLE
Special USB game controller adapter not accessable in Dolphin emulator when all permissions are enabled, but is accessable when Dolphin is ran as root

### ISSUE THREAD

**Issue by NintendoManiac64** [tchx84/Flatseal#532]
I was elated when I discovered Flatseal today since I thought that it may be able to solve the issue I've discovered semi-recently that the Dolphin emulator cannot see the official 1st party GameCube USB adapter unless you run the flatpak as root.

However, when I enabled every single permission possible in Flatseal (at least on my installation of Linux Mint 20.3 Xfce), it was still unable to see the adapter.

I don't know if there's some sort of permission that Flatseal is currently missing or what, but I would think that manually enabling all permissions in Flatseal would be equivalent to running an application as root.

　

Here's the little bit of context I can provide; unfortunately none of the Dolphin developers have ever chimed in on my issue whenever I even almost directly asked them:

- https://forums.dolphin-emu.org/Thread-flatpak-1st-party-gamecube-usb-adapter-says-access-denied-insufficient-permissions?pid=527611

- https://wiki.dolphin-emu.org/index.php?title=How_to_use_the_Official_GameCube_Controller_Adapter_for_Wii_U_in_Dolphin#Linux

(and for reference, I'm the one that added the mention on the second link that you need to run the Dolphin flatpak as root purely because it's the only way my non-Linux-guru-ness could figure out how to get this working - that does not mean there is in fact a way to get this working without the need for running as root)

Historically you would just use the non-flatpak version of Dolphin (such as the .DEB) which does not have this issue.  The problem is that .DEB variants or the like are reserved for stable releases, and Dolphin has only had beta and development releases for almost 7 years now.

**Comment by ssokolow** [comment]
That does sound like it's a permissions issue and that either the udev instructions on the Dolphin wiki are incomplete or you made a mistake when following them.

Let's see if we can track down the source of the problem.

1. Run `sudo evtest` and note the `/dev/input/eventX` path corresponding to the adapter, then type the corresponding number and verify you noted down the correct path by testing what input you're getting. Use Ctrl+C to exit.
2. Run `evtest <the path you noted down>` to make sure you can access it outside Flatpak when running as an un-privileged user. If you get "Permission denied", then it's not a Flatpak problem and you need to double-check that the udev rules from the Dolphin wiki are correct and set up correctly.  (To close one avenue for allowing one user to keylog another, Linux defaults to locking down permissions when it can't rule out that the input device might be a keyboard. The udev rule overrides the permissions for a specific model of USB device.)
3. Run `ls -l /dev/input` and check the permissions and ownership of the device node you noted down. If possible, compare them against another gamepad/joystick (i.e. another device that applications don't talk to via X11 input events) which works fine in Flatpak.
4. To play it safe, run `chacl -l <the path you noted down>` to see if there are any ACL permissions set on it beyond the basic ones provided by the classic permission bits.
5. Since the Flatpak runtime doesn't have `evtest`, try running `flatpak enter org.DolphinEmu.dolphin-emu bash` while Dolphin is running (`flatpak enter` takes you into the same environment the application is running in) and then `cat <the path you noted down>` and waggling the stick around. After using `Ctrl+C` to exit, run `reset` to make sure none of the binary data got misinterpreted as control codes to put the terminal emulator in an unexpected state, and then `exit` to drop back out of the Flatpak environment.

The next steps will depend on the result of those steps.

**Comment by NintendoManiac64** [comment]
Apologies that you've gone and typed that up, but the wiki page I linked to got changed 2 months later with a note saying "running as root is very bad advice and people should use `--device=all` instead" (and why I was never informed of this when I asked in the forum almost a year ago is beyond me...).

Of course, the irony is that this suggestion still doesn't actually work for me, so I've farther edited the wiki page.

*Anyway*, to actually respond to your post, `sudo evtest` just results in `sudo: evtest: command not found` It may be worth noting that this is not an ordinary HID nor xinput USB controller adapter as I don't believe it uses either.

**Comment by ssokolow** [comment]
> *Anyway*, to actually respond to your post, `sudo evtest` just results in `sudo: evtest: command not found`

Ahh, yeah. I forgot to check if `evtest` is one of those commands that's not all distros install by default. Sorry about that.

> It may be worth noting that this is not an ordinary HID nor xinput USB controller adapter as I don't believe it uses either.

In that case, the rough details of the process will be similar though the commands will be different.

Identify the device node(s) that is/are getting created on hotplug, and then trace it/them through the stack to identify at which point along the way the permissions are getting cut down too far.

Fortunately, my brother left behind his Mayflash Gamecube controller adapter, so I can set its switch to "Wii U/NS" and use it to try to suggest some more steps.

Check `dmesg` for a line like this after hotplugging:

`[  +0.009823] hid-generic 0003:057E:0337.000B: hiddev3,hidraw8: USB HID v1.10 Device [Nintendo WUP-028] on usb-0000:00:13.0-5/input0`

Specifically, that `hiddev3,hidraw8` bit corresponds to `/dev/usb/hiddev3` and `/dev/hidraw8` device nodes you can then check the permissions on.

Then, you can `flatpak enter` and check that they're present and appropriately permissioned for Dolphin to see.

(I can't take you all the way since my Linux PC runs an AMD CPU just old enough to lack SSE4.1, which I believe Flatpak'd Dolphin requires, and the hand-me-downs-and-spares PC of similar age (but Intel-based) that I use for gaming is running a Factory Restore of the Windows 7 that came with it to cut out things like WineD3D/VKD3D/etc. translation overhead and the finickyness of getting certain games like Dungeon Keeper 2 and Binding of Isaac: Rebirth running in Wine.)

**Comment by NintendoManiac64** [comment]
> Identify the device node(s) that is/are getting created on hotplug, and then trace it/them through the stack to identify at which point along the way the permissions are getting cut down too far.

Software is an extreme weak-point of mine, so I'm not exactly sure I would know what to do with regards to identifying the device node(s) and them and stuff...

> my Linux PC runs an AMD CPU just old enough to lack SSE4.1 which I believe Flatpak'd Dolphin requires

Are you sure that SSE4.1 is required?? In contrast to software, I know hardware like the back of my hand, and the flatpak of Dolphin is running on my own Phenom II (which only has SSE4a, not SSE4.1):

![dolphin on phenom 2](https://github.com/tchx84/Flatseal/assets/11896003/0ebe1369-b7a8-413f-8a1b-69c46f99dba7)

>  the hand-me-downs-and-spares PC of similar age (but Intel-based) that I use for gaming is running a Factory Restore of the Windows 7

What, you mean you don't have a random spare SATA disk laying around that you can just throw an installation of Linux onto? :stuck_out_tongue:   Or, shoot, the AM2/3 and LGA775/1156 boards I have of that era even have at least a single IDE port, so even that's on option.

Heck, a random spare USB drive can work as well since, unlike Windows 7, you can actually run full-fat installed Linux from USB drives.

That being said, at least in the case of Linux Mint, you can actually just run its live ISO and install the flatpak of Dolphin right through the software manager within the live session which should allow for easy enough testing (especially combined with the likes of [Ventoy](https://github.com/ventoy/Ventoy) assuming you aren't familiar with that already) and is what I show in my above screenshot.

(protip: if you live near a Micro Center, there's always their [coupon for a free 256GB SSD to new customers](http://micro.center/brokensilicon))

**Comment by ssokolow** [comment]
> Software is an extreme weak-point of mine, so I'm not exactly sure I would know what to do with regards to identifying the device node(s) and them and stuff...

Follow what I wrote next. Plug in (or unplug and re-plug) the adapter, run `dmesg`, and look for a line like this near the bottom of the output:

`[  +0.009823] hid-generic 0003:057E:0337.000B: hiddev3,hidraw8: USB HID v1.10 Device [Nintendo WUP-028] on usb-0000:00:13.0-5/input0`

That `hiddev3,hidraw8` part in my output refers to `/dev/usb/hiddev3` and `/dev/hidraw8`.

> Are you sure that SSE4.1 is required?? In contrast to software, I know hardware like the back of my hand, and the flatpak of Dolphin is running on my own Phenom II (which only has SSE4a, not SSE4.1):

To be honest, I'm not 100% sure. The last time I tried it, years ago with the distro-packaged version, it was my GeForce GTX750 that was holding me back, and I've since run into quite a few Flatpak'd emulators for PS2 or newer which die with `Illegal Instruction` on startup... when I saw that Dolphin had dropped support for Windows 7, I think I just sort of assumed it would be the same with support for my AMD CPU from 2011.

> What, you mean you don't have a random spare SATA disk laying around that you can just throw an installation of Linux onto? 😛 Or, shoot, the AM2/3 and LGA775/1156 boards I have of that era even have at least a single IDE port, so even that's on option.

I have a bowl of USB drives that I use when I need to boot temporary stuff. It's more that I lack the motivation to go through the whole process of installing a whole new OS on a flash drive, just to debug a problem I don't anticipate having any time in the near future.

> That being said, at least in the case of Linux Mint, you can actually just run its live ISO and install the flatpak of Dolphin right through the software manager within the live session which should allow for easy enough testing

I hadn't considered installing Flatpak on a Live system... but it still feels like too much work for something I'm not getting paid to do and don't anticipate ever needing.

(I've got two XBox 360 controllers, a 2-port Gamecube Mayflash adapter that's permanently wired into PC mode, and my brother's 4-port Gamecube→Wii U/Switch adapter has a PC mode.)

> (protip: if you live near a Micro Center, there's always their [coupon for a free 256GB SSD to new customers](http://micro.center/brokensilicon))

Unfortunately, I live in Canada and Micro Center doesn't appear to offer non-Zip Code locations in their location finder.

**Comment by NintendoManiac64** [comment]
I believe something has since changed. I just went through the process of installing a fresh copy of Linux Mint 21.2 Xfce (albeit in VirtualBox) only to discover that everything... just worked, and I didn't even need to use Flatseal.

At some point in the near(-ish?) future, I will also be testing this on real hardware to confirm if things also continue to "just work", after which this issue can presumably be closed.

**Comment by tchx84** [comment]
> I believe something has since changed. I just went through the process of installing a fresh copy of Linux Mint 21.2 Xfce (albeit in VirtualBox) only to discover that everything... just worked, and I didn't even need to use Flatseal.
> 
> At some point in the near(-ish?) future, I will also be testing this on real hardware to confirm if things also continue to "just work", after which this issue can presumably be closed.

Note that Flatseal is just a graphical alternative to the command line `flatpak override`.

The issue described here should have been (and probably was) fixed by the upstream project or the flatpak package maintainer.

Glad it works through :+1:
