### ISSUE TITLE
How long will Flatseal support Xorg once Wayland is forced onto Linux users?

### ISSUE THREAD

**Issue by linuxmintg** [tchx84/Flatseal#582]
I was wondering how long will Flatseal support Xorg once everyone on Linux is forced to use Wayland? Or will Flatseal always give an option for Xorg and Wayland? (Will Xorg always be an option and there's too much hype about it going away?)

I hope I have put this question the right place but I'm very concerned about Wayland and making a move over to it.

**Comment by rusty-snake** [comment]
The x11 and x11-fallback permissions will work as long as flatpak supports them (which will be a long time).

Whether flatseal can run with an x11 backend soly depends on the decisions its toolkit (GTK/libadwaita) does.

---

Nobody forces anyone to use Wayland. Wayland is just the future (MHO).

Since you use flatseal, you are probably interested in running apps in (stricter) sandboxes. In that case Wayland is better anyway. And you should consider to use it based on facts, where the facts against Wayland are mostly limited to edge-cases that are not (yet) supported.

**Comment by tchx84** [comment]
Thanks @rusty-snake for taking the time to explain this. Hopefully that was sufficient.

**Comment by linuxmintg** [comment]
Thanks for your help you 2. :)
