### ISSUE TITLE
Feature request: clean leftovers

### ISSUE THREAD

**Issue by ttoommxx** [tchx84/Flatseal#623]
I was wondering if the devs are planning on adding a feature of cleaning up leftovers from uninstalled Flatpaks, similarly to what Flatsweep does. I think it is a little wasteful to need to have both apps installed when Flatseal is far superior and does literally everything but this little thing.

**Comment by tchx84** [comment]
Hey @ttoommxx

There's two reasons why this won't happen.

1. The actual reason why Flatseal is good at managing permissions is because it's the only thing that Flatseal does. If it tried to do more than that, it would probably not be so good at managing permissions. 
2. This is a single-developer project (me), so there isn't bandwidth for extending the scope of the project.

Hope you understand.

**Comment by ttoommxx** [comment]
Hi @tchx84 , that's fair. Also I want to make sure you know that I did not mean to undermine your work, I think it's really awesome, I just feel the urge of minimising the number of apps installed :)

**Comment by tchx84** [comment]
It's all good!
