### ISSUE TITLE
No applications found. (Batocera)

### ISSUE THREAD

**Issue by juicypop** [tchx84/Flatseal#629]
I can't figure out how to solve this frequently reported issue on batocera.

This issue is related with https://github.com/tchx84/Flatseal/issues/455 but I'm a total noob when it comes to flatpak/flatseal and don't know how to solve this problem on my own.

This is how Flatseal looks like on Batocera:
![screenshot-2023 12 31-12h49 55](https://github.com/tchx84/Flatseal/assets/25671698/9a0d50f5-5e97-47d9-88cd-099d119a5c98)

This is what I tried so far and for your information:

```
[root@BATOCERA /userdata/system]# flatpak info -M com.github.tchx84.Flatseal
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=xdg-data/flatpak/overrides:create;/var/lib/flatpak/app:ro;xdg-data/flatpak/app:ro;

[Session Bus Policy]
org.gnome.Software=talk
org.freedesktop.impl.portal.PermissionStore=talk
```
```
[root@BATOCERA /userdata/system]# which flatpak
/usr/bin/flatpak
```
If I undestand correctly, this indicates I'm running a custom flatpak install, but Flatseal won't let me set the needed settings in it's UI.

So I guess I should do the following?:
```
[root@BATOCERA /userdata/system]# flatpak --user override --filesystem=/userdata/saves/flatpak --env=FLATPAK_USER_DIR=/userdata/
saves/flatpak --filesystem=/usr/bin/flatpak:ro --filesystem=host-etc:ro com.github.tchx84.Flatseal

```
- /userdata/saves contains the folder `flatpak` where flatpaks are installed on batocera, or should it be `/userdata/saves/flatpak` instead?
- are these correct as I can't set them in the UI?
- - `--filesystem=/usr/bin/flatpak:ro` 
- - `--filesystem=host-etc:ro`

Oh and by the way, what is `xdg-data/flatpak/overrides` or `xdg-data/flatpak/app`?
Are they related to the env FLATPAK_USER_DIR == xdg-data ?

This is how it looks like after my modification I think I need to apply in order to fix Flatseal not seeing any applications:
```
[root@BATOCERA /userdata/system]# flatpak info -M com.github.tchx84.Flatseal
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=host-etc:ro;/usr/bin/flatpak:ro;xdg-data/flatpak/overrides:create;/userdata/saves/flatpak;/var/lib/flatpak/app:ro;xdg-data/flatpak/app:ro;

[Session Bus Policy]
org.gnome.Software=talk
org.freedesktop.impl.portal.PermissionStore=talk

[Environment]
FLATPAK_USER_DIR=/userdata/saves/flatpak
```

I really hope someone can help me to fix this issue.
Thanks in advance.

**Comment by tchx84** [comment]
@juicypop apologies for the delay, questions:

1. Where does Batocera installs flatpak applications by default? e.g.,`ls /var/lib/flatpak/app`
2. What happens if you install apps on the user installation? e.g. `flatpak --user install flathub dev.tchx84.Portfolio`
3. Are you using a custom installation ? e.g. `ls /etc/flatpak/installations.d`

**Comment by tchx84** [comment]
Please re-open if you're still having this issue.

**Comment by jaredhenderson** [comment]
Hi @tchx84,
Wondering if I can hijack this issue as I am encountering the same problem in Batocera. I believe this is due to a non-standard default directory for Flatpaks with this distro.

Answering your previous questions:
1. Flatpaks are saved in `/userdata/saves/flatpak` ([wiki](https://wiki.batocera.org/systems:flatpak))
```
[root@BATOCERA /]# ls -g /userdata/saves/flatpak
drwxr-xr-x 8 root 4096 Oct 22 14:45 binaries
drwxr-xr-x 7 root 4096 Oct 21 17:51 data

[root@BATOCERA /]# ls -g /userdata/saves/flatpak/binaries
drwxr-xr-x  7 root 4096 Oct 22 14:45 app
drwxr-xr-x  3 root 4096 Oct 21 17:17 appstream
drwxr-xr-x  4 root 4096 Oct 21 17:16 exports
drwxr-xr-x  7 root 4096 Oct 22 14:45 repo
drwxr-xr-x 18 root 4096 Oct 22 14:45 runtime

[root@BATOCERA /]# ls -g /userdata/saves/flatpak/binaries/app
drwxr-xr-x 3 root 4096 Oct 22 14:45 com.github.tchx84.Flatseal
drwxr-xr-x 3 root 4096 Oct 21 17:18 com.heroicgameslauncher.hgl
drwxr-xr-x 3 root 4096 Oct 21 17:16 com.valvesoftware.Steam
drwxr-xr-x 3 root 4096 Oct 21 22:30 io.github.philipk.boilr
drwxr-xr-x 3 root 4096 Oct 22 14:45 io.missioncenter.MissionCenter
```

2. Results of user install:
```
[root@BATOCERA /]# flatpak --user install flathub dev.tchx84.Portfolio

Note that the directory 

'/userdata/saves/flatpak/data/.local/share/flatpak/exports/share'

is not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Looking for matches…

dev.tchx84.Portfolio permissions:
    ipc                    fallback-x11             wayland                       x11        dri
    file access [1]        bus ownership [2]        system dbus access [3]

    [1] /media, /run/media, home
    [2] org.freedesktop.FileManager1
    [3] org.freedesktop.UDisks2


        ID                                    Branch           Op          Remote           Download
 1. [✓] dev.tchx84.Portfolio.Locale           stable           i           flathub           2.3 kB / 21.8 kB
 2. [✓] dev.tchx84.Portfolio                  stable           i           flathub          47.5 kB / 62.1 kB

Installation complete.

```
```
[root@BATOCERA /]# flatpak info --show-location dev.tchx84.Portfolio
/userdata/saves/flatpak/data/.local/share/flatpak/app/dev.tchx84.Portfolio/x86_64/stable/09167aa0128a1b7c598aab253e4d0ac9a124dd5b9626e4f703f428cc242dc52f
```

3. I believe it is a custom directory but not the one from your example:
```
[root@BATOCERA /]# ls /etc/flatpak/installations.d
ls: cannot access '/etc/flatpak/installations.d': No such file or directory
```

Here is the current info for Flatseal if that helps (I have added some env variables in an attempt to pick up the existing installed applications but this doesn't seem to have helped):
```
[root@BATOCERA /]# flatpak info -M com.github.tchx84.Flatseal
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=xdg-data/flatpak/overrides:create;/userdata/saves/flatpak;/var/lib/flatpak/app:ro;xdg-data/flatpak/app:ro;

[Session Bus Policy]
org.gnome.Software=talk
org.freedesktop.impl.portal.PermissionStore=talk

[Environment]
FLATPAK_SYSTEM_DIR=/userdata/saves/flatpak
```

**Comment by jaredhenderson** [comment]
Further to the above: it appears that adding your Portfolio app as a user installation makes it visible to Flatseal with my existing config:

![screenshot-2024 10 22-15h47 59](https://github.com/user-attachments/assets/ee4db7a1-8114-42b6-992f-0b1b65e85952)

**Comment by tchx84** [comment]
@jaredhenderson How is batocera changing this directory ?

Have you tried the options mentioned here https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations ?

EDIT: Also, try  https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#use-custom-flatpak_user_dir setting FLATPAK_SYSTEM_DIR

**Comment by jaredhenderson** [comment]
Hi @tchx84, thanks for your help. I have tried setting the `FLATPAK_SYSTEM_DIR` variable to another directory (and given Flatseal filesystem access to that directory) and it looks like that worked:

`flatpak override --env=FLATPAK_SYSTEM_DIR=/userdata/saves/flatpak/binaries --filesystem=/userdata/saves/flatpak com.github.tchx84.Flatseal`

![screenshot-2024 10 25-14h04 48](https://github.com/user-attachments/assets/684eaf7c-d54c-4306-b9d1-15c4d2708793)

I don't have much experience looking at Flatpak configurations on other distros so I can't really say what Batocera is doing differently (other than having a custom location, and not having the `installations.d` directory you mentioned).

Looks to be working now so hopefully that was all that's required. Thanks again! 🙂

**Comment by jaredhenderson** [comment]
Perhaps I spoke too soon, looks like Flatpak added for the system via `override` aren't being detected. They are detected when using `override --user`. Perhaps this is by design?

Example:
`flatpak override --filesystem=/userdata/saves/flatpak/data/.var/app com.steamgriddb.steam-rom-manager`
`[root@BATOCERA /userdata/system]# flatpak override --show com.steamgriddb.steam-rom-manager
[Context]
filesystems=/userdata/saves/flatpak/data/.var/app;`

Result in Flatseal:
![screenshot-2024 10 25-15h22 15](https://github.com/user-attachments/assets/bc440861-9ab4-48e3-9946-6ccd259bc041)

Looks like system overrides are stored in:
`/userdata/saves/flatpak/binaries/overrides`

User overrides are in:
`/userdata/saves/flatpak/data/.local/share/flatpak/overrides`

Flatseal has directory access to `/userdata/saves/flatpak`. When I make a modification with Flatseal, it is saved to the user overrides location.

For now I will just move all my overrides into the user space as Batocera is a single-user environment anyway.
