### ISSUE TITLE
No expansion of nested environment variables in environment variable overrides

### ISSUE THREAD

**Issue by 6b6279** [tchx84/Flatseal#674]
Hello,

I am not sure if this is a shortcoming of Flatpak itself, but it seems like nested envvars in envvar overwrites are not evaluated, e.g., the overwrite `MYDATADIR=$XDG_DATA_HOME/custom` isn't evaluated into `MYDATADIR=/home/foo/.var/app/foo.bar.Example/data/custom`, but according to `flatpak run --command=sh --devel`, it's declared literally, so that the variable literally contains the substring `$XDG_DATA_HOME`.

I've discovered this trying to set `DOOMWADDIR` for Crispy Doom: https://github.com/fabiangreffrath/crispy-doom/issues/1193

**Comment by rusty-snake** [comment]
There is no concept of "nested environment variables" in POSIX (i.e. `setenv(3)`/`getenv(3)`). They are plain strings w/o any logic/runtime beyond `<NAME>=<VALUE>`. `FOOBAR=$FOO/bar` in bash works because the right side is evaluated with features such as "parameter expansion" or "command substitution".

Flatseal could (=technically possible) expand those variables at the time when you enter/save them but not when you `flatpak run`. This is likely not what you want since you could also just enter the expanded path. (And `$XDG_DATA_HOME` might have an unexpected value due to flatpak).

As you already said, this limitation comes from flatpak. Where I could find two relevant issues:

https://github.com/flatpak/flatpak/issues/4596
https://github.com/flatpak/flatpak/issues/1415

**Comment by 6b6279** [comment]
I see. Like you said, if Flatseal were to expand envvars upon "entry" (e.g., string replacement in the entry field), it'd cause other issues, ex., `$XDG_DATA_HOME` being incorrectly replaced. I guess I am better off manually typing in the exact paths.
