### ISSUE TITLE
Display only the portals the flatpak asks for

### ISSUE THREAD

**Issue by thibaultamartin** [tchx84/Flatseal#77]
Hello and thanks a lot for Flatseal, this is a really handy utility!

In latest stable (`1.5.3` as of the opening of this issue), Flatseal seems to display every portal possible, for each flatpak.

It could simplify the UI and be more accessible for the end-user if it only displayed the portals the flatpak asks for (which the end user can then enable or disable)

**Comment by tchx84** [comment]
Hey @thibaultamartin ,

Thanks for the feedback!

Permissions and Portals are fundamentally different things.

Permissions are explicit properties defined even before the application is built. You can find these in the application manifest or metadata.

Portals are APIs that can be invoked only when the application is already running. These require an explicit action from the user (e.g. through a dialog) to allow the application to access a resource.

Because of that, it would make no sense for Flatseal to try to deal with Portals.

What Flatseal does is to manage Permissions, only.

**Comment by thibaultamartin** [comment]
Ah, here I stand corrected! Wrong choice of words, but the idea remains: is it technically feasible to display only the permissions the application asks for, through its manifest or metadata?

**Comment by tchx84** [comment]
> Ah, here I stand corrected! Wrong choice of words, but the idea remains: is it technically feasible to display only the permissions the application asks for, through its manifest or metadata?

I don't think I understand your proposal :confused: Can you clarify what you mean by "the application asks"?

Permissions are never "asked for" they are already granted when you install the application. What Flatseal allows you to do is 1) See _all_ permissions enabled and disabled by the application by default, 2) disable the ones you don't want, and 3) enable the ones you do want.

Only Portals API calls are "asked for", as I explained above.

**Comment by thibaultamartin** [comment]
Ha, sorry about that, I'll trying putting it another way. "Asking" is a poor choice of words here too indeed.

Let's try with an example. Consider the Obfuscate flatpak. In its manifest it doesn't say it needs network. So by default, the network permission is disabled.

![flatseal_obfuscate](https://user-images.githubusercontent.com/1688309/82709970-1463fc80-9c82-11ea-9633-871d11909146.png)

Unless I'm missing something, it makes little sense to grand Obfuscate the "network" permission since it will never use it. I will leave it to "off" anyway, since I don't want to grant unnecessary permissions to Obfuscate.

Does it make sense to display the "network" permission toggle, if it's never going to be turned on?

This would basically mean that when an app gets installed and you open flatseal, you would only see the permissions present in the manifest, and by default all the switches would be turned on (since the permissions not present in the manifest would not be visible).

**Comment by tchx84** [comment]
> Unless I'm missing something,

You are missing something, indeed :) There are many cases where a permission is disabled by default, but where it makes sense to enable it.

e.g. I happen to maintain a Python editor for kids where, by default, the network permission is disabled to make it more secure. But more advance users might want to do network programming, so they would need to enable that permission.

e.g Steam users are probably the most common users of Flatseal currently, since they need to enable custom directories for Steam to find their games.

> it makes little sense to grand Obfuscate the "network" permission since it will never use it. I will leave it to "off" anyway, since I don't want to grant unnecessary permissions to Obfuscate.
> 
> Does it make sense to display the "network" permission toggle, if it's never going to be turned on?
> 

Yes it does and, just as the examples I mentioned above, there are many other cases where users might _need_ to enable permissions that were not granted by default.

In fact, my guess is that enabling permissions that were not granted by default is probably the most common use case.

**Comment by thibaultamartin** [comment]
Ah thanks for letting me know! It seems I only had a very basic usage of flatseal :)

I’m closing this issue then, thanks for your time, explanations, and keep up the good work!

**Comment by tchx84** [comment]
> Ah thanks for letting me know! It seems I only had a very basic usage of flatseal :)
> 
> I’m closing this issue then, thanks for your time, explanations, and keep up the good work!

All good, and thanks for the feedback!

**Comment by johnfactotum** [comment]
Maybe it can show only the default and modified permissions, and have a "+" button which will allow one to add other permissions?

- When disabling existing permissions, showing only the default and modified ones means the user won't be overwhelmed by irrelevant permissions.
- For adding permissions, an "add permission" dialog will also be more convenient. Instead of hunting for the permission in a long list, one can implement a wizard-like UI to make things easier. (Bonus: one can even have customized "add permission" UI for each app or category of apps. Now, I know that's probably not realistic to maintain, but it's just an idea.)
