### ISSUE TITLE
Folder browser portal for folder permissions

### ISSUE THREAD

**Issue by Eonfge** [tchx84/Flatseal#8]
Let me quickly preface that I really like your app. I've previously thought of such a thing myself so to see your app suddenly on Flathub is really cool.

One thing I would add, is I would replace the folder-exceptions input with a folder browser portal. That way, users can visually select the folders they want to give additional access too. This is both easier to configure, and it prevents accidental mis-configurations

**Comment by tchx84** [comment]
I considered that too, sadly I don't have the time to focus on that at the moment, but I would accept PRs ;)

**Comment by Eonfge** [comment]
@tchx84 We're all short on time, but I'll see what I can do. I certainly like the project and I think it's a good addition to the Flatpak ecosystem.

**Comment by tchx84** [comment]
Maybe @bertob can help us design this widget ?

**Comment by bertob** [comment]
Could you outline the requirements/constraints for this?

For example, is there a known fixed number of XDG folders we could just all show and have toggles for? How are other folders specified? How does the :ro wildcard thing work?

**Comment by tchx84** [comment]
> Could you outline the requirements/constraints for this?
> 
> For example, is there a known fixed number of XDG folders we could just all show and have toggles for? How are other folders specified? How does the :ro wildcard thing work?

We could have toggles for xdg directories, yes, but I am unsure we want to "pollute" the UI with so many of these.

Other "custom" folders are specified by a path, e.g. `~/Projects` or `/home/tchx84/Projects` or any other path.

The `:ro` suffix means "read-only". 

What we currently have is basically one GtkEntry with all of these xdg + custom paths separated by `;`, which is how flatpak stores it internally.

What I think we should have is:

1. Some sort of graphical representation for the same thing, but where each directory is clearly visible and visually independent of the other paths.
2. Some sort of visual cue for showing whether is read-only or writable.
3. Options to remove these directories.
4. An option to add new directories.

What I imagined originally is a widget where each directory is displayed as an independent Label (which could look like [this](https://i1.wp.com/growonyoutube.com/wp-content/uploads/2017/06/Screen-Shot-2017-06-10-at-12.34.31.png?ssl=1)), including the `x` button to remove a directory. Plus, a `+` button somewhere to open a file chooser to add more.

**Comment by tchx84** [comment]
Expanding a bit on xdg directories, the widget could give special treatment to these and display these with their real path, e.g. `xdg-download` would show as `~/Downloads`, so the widget will consistently show real paths and not just  weird* keywords.

weird* for people who doesn't know what xdg-* means.

**Comment by tchx84** [comment]
I already started working on a prototype widget, ill post some screenshots here soon.

**Comment by tchx84** [comment]
A "brief" update on the things I decided **not** to do, and what I ended-up doing:

1. Using file chooser to select files and directories:
* Can't use the document portal to select files, because you won't get the real file path anyway.
* Can't use the document portal to select directories, because is not supported at all.

2. Displaying real paths instead of xdg-* tokens:
* Can't use GLib.get_user_special_dir() without having permissions to these directories.

Basically, I can't do any of those things without giving even more permissions to this app, and I don't think is worth it.

Therefore, I prototyped something a bit different, still requires to type-in these paths like before, but it should be a lot easier to manage these.

![Screenshot from 2020-02-11 18-03-37](https://user-images.githubusercontent.com/481418/74279430-a8c0d980-4cf9-11ea-8808-fbcd99c3cdcd.png)

Now each path is displayed individually. Each of these "tag" looking entries is a GtkEntry so you can edit paths right there. You can also remove any of these paths by just "clicking" on the `x` button.

![Screenshot from 2020-02-11 18-03-56](https://user-images.githubusercontent.com/481418/74279639-0ce39d80-4cfa-11ea-893a-a5a728ddc178.png)

To add a new path, simply click on that button and a new entry is added, ready to be edited.

![Screenshot from 2020-02-11 18-04-11](https://user-images.githubusercontent.com/481418/74279744-41575980-4cfa-11ea-89e9-020ec258f564.png)

Plus, each of these "tag" looking entries has a style class (`ready-only`, `readwrite`, and `create`), which I am not currently using. I played with the idea of giving special background colors depending on the class, but was not convinced with the results.

**Comment by tchx84** [comment]
Here's a screenshot in "mobile" mode :)

![Screenshot from 2020-02-11 20-04-01](https://user-images.githubusercontent.com/481418/74287850-b54d2e00-4d09-11ea-896f-1c5d4be30b17.png)

**Comment by bertob** [comment]
This looks much better, but I'd suggest left-aligning the file paths.

**Comment by tchx84** [comment]
> This looks much better, but I'd suggest left-aligning the file paths.

Thanks :)

I originally had left-aligned but it felt wrong somehow, I suspected because of two things: a) all other options are aligned to the left and it felt (visually) odd, and b) it's easier to manipulate the path list if you have the close button right next to each path, also, in mobile mode, you want your thumb to stay aligned vertically the whole time as you scroll the page and select things.

**Comment by bertob** [comment]
I don't quite follow the reasoning, do you have a screenshot where they're left-aligned?

**Comment by tchx84** [comment]
There it goes!

![Screenshot from 2020-02-20 17-04-50](https://user-images.githubusercontent.com/481418/74974064-540d1500-5403-11ea-9b0f-b1530e3f7ffa.png)
![Screenshot from 2020-02-20 17-05-42](https://user-images.githubusercontent.com/481418/74974080-596a5f80-5403-11ea-90d3-57ac335d64b9.png)

One reasoning is:
1. All manipulable options are right-aligned (imagine having a phone in your right hand and manipulating these options with your thumb).
2. Therefore, the button to remove these directories / files is also right-aligned.
3. It is easier to spot which directory / file you are manipulating if you have it right next to its button.

The other part of the reasoning is harder to explain hah, but is just feels visually odd to me.

**Comment by bertob** [comment]
These screenshots look way clearer to me, I don't see the problem at all :D

**Comment by tchx84** [comment]
Alright, let's give it a try in the next release.
